# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\ci\containers\00001370aum\tmp\build\80754af9\rsync-recipes\python-3.7.0-cxx_compiler_vs2015-vc_14-c_compiler_vs2015-on-winbuilder, last modified Thu Jun 28 06:53:15 2018
# ------------------------------------------------

package:
    name: python
    version: 3.7.0
source:
    -   md5: eb8c2a6b1447d50813c02714af4681f3
        patches:
            - 0001-Add-Anaconda-Distribution-version-logic.patch
            - 0002-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - 0003-Win32-distutils-Also-look-for-executable.bat.patch
            - 0005-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - 0006-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - 0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - 0008-Support-cross-compiling-byte-code.patch
            - 0009-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - 0010-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - 0011-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - 0012-Win32-Do-not-download-externals.patch
            - 0013-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - 0014-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - 0015-Disable-new-dtags-in-unixccompiler.py.patch
        url: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
    -   folder: externals/xz-5.2.2
        sha256: 02b6d6f1e0369940e7e1f0d324992e069d09f5f3d32d86e2d22cd8b82ac3fb3f
        url: https://github.com/python/cpython-source-deps/archive/xz-5.2.2.zip
    -   folder: externals/tcl-core-8.6.8.0
        sha256: 91fd3ea97f7fddbd45591fd91961b6be6434b6d338ae54ad16f40efe53295be2
        url: https://github.com/python/cpython-source-deps/archive/tcl-core-8.6.8.0.zip
    -   folder: externals/tk-8.6.8.0
        sha256: 584fbfdc3cd4427d44ae7ba1e829966d30aaee2a36feb02e3714ac97b48983c1
        url: https://github.com/python/cpython-source-deps/archive/tk-8.6.8.0.zip
    -   folder: externals/tcltk-8.6.8.0
        sha256: 63a28d9112d47f5ca9970593fda7fca8c22e911450d8036e033bba376500acd9
        url: https://github.com/python/cpython-bin-deps/archive/tcltk-8.6.8.0.zip
    -   folder: externals/tix-8.4.3.6
        sha256: e558e3dc5e67ac0942f8fceafce00ca46b177da9ebeaf38ec7fafd9b9913ac56
        url: https://github.com/python/cpython-source-deps/archive/tix-8.4.3.6.zip
    -   folder: externals/sqlite-3.21.0.0
        sha256: 95a4f2d76aeeb68b51239340e3de26e5714ecfb7c8ad82a67b17af82213a8c20
        url: https://github.com/python/cpython-source-deps/archive/sqlite-3.21.0.0.zip
    -   folder: externals/openssl-1.1.0f
        sha256: f9a39b7519d3c1d5b5da7559c0b117f588eea97bc98d4ea8434d078cf5063eaa
        url: https://github.com/python/cpython-source-deps/archive/openssl-1.1.0f.zip
    -   folder: externals/openssl-bin-1.1.0h
        sha256: 8388d90b06b878a7fd980a46264d2d2aca2900ce36dd6834cf85861921534c35
        url: https://github.com/python/cpython-bin-deps/archive/openssl-bin-1.1.0h.zip
    -   folder: externals/bzip2-1.0.6
        sha256: c42fd1432a2667b964a74bc423bb7485059c4a6d5dc92946d59dbf9a6bdb988d
        url: https://github.com/python/cpython-source-deps/archive/bzip2-1.0.6.zip
    -   folder: externals/zlib-1.2.11
        sha256: debb1952945fa6c25817a40abe90641b572c83171f244937b70b9fe156f5a63a
        url: https://github.com/python/cpython-source-deps/archive/zlib-1.2.11.zip
    -   folder: externals/nasm-2.11.06
        sha256: de3c87b26a80e789986d8e6950c6304175d3829afe9c6c7211eb7257266ab0ac
        url: https://github.com/python/cpython-bin-deps/archive/nasm-2.11.06.zip
build:
    no_link:
        - DLLs/_ctypes.pyd
    string: hea74fb7_0
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
    run:
        - vc 14.*
test:
    commands:
        - python -V
        - 2to3 -h
        - pydoc -h
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
